# knot — 03: schema evolution via Atlas

knot is a *compiler* — `Spec.ddl()` returns the canonical target
schema as one idempotent script. **Migrations against a live DB
are someone else's problem**: knot hands you the schema you want,
you pipe it through your team's existing schema-diff tool
([Atlas](https://atlasgo.io/) is the tested default; see
`CLAUDE.md` §"Schema deployment" for alternatives) to get the
reconciling SQL.

This notebook walks through the loop end-to-end:

1. Build spec v1, deploy to a fresh schema.
2. Mutate the spec in place to grow a slot, a class, and a vector
   column.
3. Hand v2's DDL to `atlas schema diff` and read the SQL it
   proposes.
4. `atlas schema apply` to land the schema change.
5. Re-run `Spec.ddl()` to rebuild views (Atlas community doesn't
   manage them — `CREATE OR REPLACE` is unconditional and cheap).
6. Confirm the new shape with `\\d`.

The whole pitch: **what about migrations** has the same answer as
**what about connections**. knot doesn't own either; the host
composes knot's output with the tools the team already trusts.

In [2]:
import subprocess
from pathlib import Path

import pandas as pd
import psycopg

In [3]:
# Connect to the live postgres + ensure Atlas's dev DB exists.
# Atlas needs a clean throwaway DB to render the desired schema
# state; one CREATE DATABASE is the whole setup cost.
pg = psycopg.connect(
    host="localhost",
    port=5433,
    user="knot",
    password="knot",
    dbname="knot",
    autocommit=True,
)
with psycopg.connect(
    host="localhost",
    port=5433,
    user="knot",
    password="knot",
    dbname="postgres",
    autocommit=True,
) as admin:
    admin.execute("DROP DATABASE IF EXISTS atlas_dev")
    admin.execute("CREATE DATABASE atlas_dev")

SCHEMA = "knot_demo"
pg.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
SCHEMA

'knot_demo'

## v1 — Person only

The starting spec is deliberately small: one class, one slot. The
point is to demonstrate the *change*, not the spec.

In [4]:
from knot import Spec, types

spec = Spec(identifier_slot_name="canonical_id")
person = spec.add_class("Person")
person.slot("name", types.TEXT, required=True)
spec

Spec(identifier_slot_name='canonical_id', classes=[OntologyClass(name='Person', kind=<ClassKind.CONCRETE: 'concrete'>, is_a=None, mixins=[], slots=[Slot(name='canonical_id', type=<Primitive.TEXT: 'text'>, identifier=True, required=True, description=None), Slot(name='name', type=<Primitive.TEXT: 'text'>, identifier=False, required=True, description=None)], description=None)], sources=[], source_bindings=[], constraints=[], identifier_type=<Primitive.TEXT: 'text'>)

In [5]:
# Deploy v1: idempotent CREATE script, executed directly. This is
# the "first deploy" path — no diff tool needed, just run it.
pg.execute(spec.ddl(schema=SCHEMA))

In [6]:
# What landed?
pd.read_sql_query(
    "SELECT table_name, table_type FROM information_schema.tables "
    "WHERE table_schema = %(schema)s "
    "UNION ALL "
    "SELECT viewname, 'VIEW' FROM pg_views WHERE schemaname = %(schema)s "
    "ORDER BY 2, 1",
    pg,
    params={"schema": SCHEMA},
)

/tmp/ipykernel_2733170/1413246010.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(

           table_name  table_type
0              person  BASE TABLE
1     person_bindings  BASE TABLE
2       source_weight  BASE TABLE
3  person_all_sources        VIEW
4  person_all_sources        VIEW
5     person_resolved        VIEW
6     person_resolved        VIEW

## v2 — mutate the spec in place

We grow `Person` with a `birth_country` slot, add a new `Movie`
class with an FK to `Person`, and stick a `title_embedding`
`VECTOR(384)` slot on `Movie`. Pure spec edit — no SQL touched
by hand.

In [7]:
# Mutate in place — this is the "real" migration story: one spec
# object grows over time. There's no `spec_v2` rebuild.
person.slot("birth_country", types.TEXT)
movie = spec.add_class("Movie")
movie.slot("title", types.TEXT, required=True)
movie.slot("year", types.INTEGER)
movie.slot("director", person)
movie.slot("title_embedding", types.VECTOR(384))
movie

OntologyClass(name='Movie', kind=<ClassKind.CONCRETE: 'concrete'>, is_a=None, mixins=[], slots=[Slot(name='canonical_id', type=<Primitive.TEXT: 'text'>, identifier=True, required=True, description=None), Slot(name='title', type=<Primitive.TEXT: 'text'>, identifier=False, required=True, description=None), Slot(name='year', type=<Primitive.INTEGER: 'integer'>, identifier=False, required=False, description=None), Slot(name='director', type=ClassRef(target=OntologyClass(name='Person', kind=<ClassKind.CONCRETE: 'concrete'>, is_a=None, mixins=[], slots=[Slot(name='canonical_id', type=<Primitive.TEXT: 'text'>, identifier=True, required=True, description=None), Slot(name='name', type=<Primitive.TEXT: 'text'>, identifier=False, required=True, description=None), Slot(name='birth_country', type=<Primitive.TEXT: 'text'>, identifier=False, required=False, description=None)], description=None)), identifier=False, required=False, description=None), Slot(name='title_embedding', type=Vector(dim=384, metric='cosine'), identifier=False, required=False, description=None)], description=None)

## Emit v2 DDL → write to a file Atlas can read

`include_views=False` because Atlas community doesn't manage
views, and knot's `_resolved` / `_all_sources` views use
`FILTER (WHERE …)` that some sqldef parsers don't accept. We
handle views ourselves in the last step.

In [8]:
target_sql = Path("/tmp/knot_target.sql")
target_sql.write_text(spec.ddl(schema=SCHEMA, include_views=False))
print(f"wrote {target_sql} ({target_sql.stat().st_size} bytes)")

wrote /tmp/knot_target.sql (2678 bytes)

## `atlas schema diff` — read the proposed migration

Atlas introspects the live DB (`--from`), loads the target SQL
into the throwaway dev DB to render the desired state (`--to` +
`--dev-url`), and prints the reconciling SQL. Nothing is applied
yet — this is the review step.

In [9]:
diff_cmd = [
    "atlas",
    "schema",
    "diff",
    "--from",
    "postgres://knot:knot@localhost:5433/knot?sslmode=disable",
    "--to",
    f"file://{target_sql}",
    "--dev-url",
    "postgres://knot:knot@localhost:5433/atlas_dev?sslmode=disable",
    "-s",
    SCHEMA,
]
diff = subprocess.run(diff_cmd, capture_output=True, text=True, check=True)
print(diff.stdout)

-- Modify "person" table
ALTER TABLE "knot_demo"."person" ADD COLUMN "birth_country" text NULL;
-- Modify "person_bindings" table
ALTER TABLE "knot_demo"."person_bindings" ADD COLUMN "birth_country" text NULL;
-- Create "movie_bindings" table
CREATE TABLE "knot_demo"."movie_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "title" text NULL, "year" integer NULL, "director" text NULL, "title_embedding" public.vector(384) NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "movie_bindings_current_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_current_idx" ON "knot_demo"."movie_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "movie_bindings_source_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_source_idx" ON "knot_demo"."movie_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "movie_bindings_title_embedding_hnsw_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_title_embedding_hnsw_idx" ON "knot_demo"."movie_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "movie" table
CREATE TABLE "knot_demo"."movie" ("canonical_id" text NOT NULL, "title" text NOT NULL, "year" integer NULL, "director" text NULL, "title_embedding" public.vector(384) NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_movie_director" FOREIGN KEY ("director") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "movie_title_embedding_hnsw_idx" to table: "movie"
CREATE INDEX "movie_title_embedding_hnsw_idx" ON "knot_demo"."movie" USING hnsw ("title_embedding" vector_cosine_ops);

## `atlas schema apply` — land the change

Same args, `--auto-approve` because this is a demo. In a real
deployment you'd review the diff first, run apply interactively,
or commit the diff to a versioned-migrations directory.

In [10]:
apply_cmd = [
    "atlas",
    "schema",
    "apply",
    "--url",
    "postgres://knot:knot@localhost:5433/knot?sslmode=disable",
    "--to",
    f"file://{target_sql}",
    "--dev-url",
    "postgres://knot:knot@localhost:5433/atlas_dev?sslmode=disable",
    "-s",
    SCHEMA,
    "--auto-approve",
]
apply_result = subprocess.run(apply_cmd, capture_output=True, text=True, check=True)
print(apply_result.stdout)

-- Planned Changes:
-- Modify "person" table
ALTER TABLE "knot_demo"."person" ADD COLUMN "birth_country" text NULL;
-- Modify "person_bindings" table
ALTER TABLE "knot_demo"."person_bindings" ADD COLUMN "birth_country" text NULL;
-- Create "movie_bindings" table
CREATE TABLE "knot_demo"."movie_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "title" text NULL,
  "year" integer NULL,
  "director" text NULL,
  "title_embedding" public.vector(384) NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "movie_bindings_current_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_current_idx" ON "knot_demo"."movie_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "movie_bindings_source_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_source_idx" ON "knot_demo"."movie_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "movie_bindings_title_embedding_hnsw_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_title_embedding_hnsw_idx" ON "knot_demo"."movie_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "movie" table
CREATE TABLE "knot_demo"."movie" (
  "canonical_id" text NOT NULL,
  "title" text NOT NULL,
  "year" integer NULL,
  "director" text NULL,
  "title_embedding" public.vector(384) NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_movie_director" FOREIGN KEY ("director") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "movie_title_embedding_hnsw_idx" to table: "movie"
CREATE INDEX "movie_title_embedding_hnsw_idx" ON "knot_demo"."movie" USING hnsw ("title_embedding" vector_cosine_ops);

## Rebuild views via knot

Atlas community didn't touch views. `Spec.ddl()` is idempotent
throughout (`CREATE TABLE IF NOT EXISTS` / `CREATE OR REPLACE
VIEW`), so re-executing the full thing is safe — the table
statements are no-ops since Atlas already brought them in line,
and the views get rebuilt against the new schema shape.

In [11]:
pg.execute(spec.ddl(schema=SCHEMA))

## Confirm — final shape

Tables, columns, indexes (including the HNSW index on the new
vector slot), and the regenerated views.

In [12]:
relations = pd.read_sql_query(
    "SELECT table_name AS name, table_type AS kind "
    "FROM information_schema.tables WHERE table_schema = %(schema)s "
    "UNION ALL "
    "SELECT viewname, 'VIEW' FROM pg_views WHERE schemaname = %(schema)s "
    "ORDER BY 2, 1",
    pg,
    params={"schema": SCHEMA},
)
relations

/tmp/ipykernel_2733170/1759714735.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  relations = pd.read_sql_query(

                  name        kind
0                movie  BASE TABLE
1       movie_bindings  BASE TABLE
2               person  BASE TABLE
3      person_bindings  BASE TABLE
4        source_weight  BASE TABLE
5    movie_all_sources        VIEW
6    movie_all_sources        VIEW
7       movie_resolved        VIEW
8       movie_resolved        VIEW
9   person_all_sources        VIEW
10  person_all_sources        VIEW
11     person_resolved        VIEW
12     person_resolved        VIEW

In [13]:
# movie_bindings columns — note the new title_embedding vector(384).
pd.read_sql_query(
    "SELECT column_name, data_type, is_nullable "
    "FROM information_schema.columns "
    "WHERE table_schema = %(schema)s AND table_name = 'movie_bindings' "
    "ORDER BY ordinal_position",
    pg,
    params={"schema": SCHEMA},
)

/tmp/ipykernel_2733170/2485223125.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(

          column_name                 data_type is_nullable
0         source_name                      text          NO
1   source_identifier                      text          NO
2        canonical_id                      text         YES
3               title                      text         YES
4                year                   integer         YES
5            director                      text         YES
6     title_embedding              USER-DEFINED         YES
7         raw_payload                     jsonb          NO
8         er_metadata                     jsonb          NO
9          valid_from  timestamp with time zone          NO
10           valid_to  timestamp with time zone         YES

In [14]:
# movie_bindings indexes — including the HNSW Atlas built.
pd.read_sql_query(
    "SELECT indexname, indexdef FROM pg_indexes "
    "WHERE schemaname = %(schema)s AND tablename = 'movie_bindings' "
    "ORDER BY indexname",
    pg,
    params={"schema": SCHEMA},
)

/tmp/ipykernel_2733170/200624557.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(

,indexname,indexdef
0,movie_bindings_current_idx,CREATE INDEX movie_bindings_current_idx ON kno...
1,movie_bindings_pkey,CREATE UNIQUE INDEX movie_bindings_pkey ON kno...
2,movie_bindings_source_idx,CREATE INDEX movie_bindings_source_idx ON knot...
3,movie_bindings_title_embedding_hnsw_idx,CREATE INDEX movie_bindings_title_embedding_hn...

## What this demo doesn't show (honest caveats)

- **Rename detection.** Atlas can't tell a rename from a
  drop-and-add; if you rename a slot in the spec, the diff will
  look like "drop old column, add new column" with data loss.
  Use Atlas's `--declare-renames` or write a `pre-migration` HCL
  script. Same blind spot every autogen has.
- **Backfills.** Adding a `NOT NULL` column to a non-empty table
  needs an `UPDATE` first. Atlas surfaces the destructive op;
  the host owns the backfill.
- **Vector dim/metric changes.** If you change `VECTOR(384)` →
  `VECTOR(768)`, Atlas correctly detects the column-type
  change — but every existing row's embedding has to be
  recomputed by your embedding worker before the migration is
  meaningful. The schema change is mechanical; the data
  migration is your problem.
- **Versioned migrations / down migrations / drift detection
  over time.** Atlas supports all of these via its
  `atlas migrate` subcommand (versioned-migrations directory).
  This notebook uses `schema apply` for simplicity; production
  probably wants the versioned-migrations workflow.

The point isn't that this demo handles every case — it's that
the *story* is honest: knot emits the schema, Atlas reconciles,
your team owns the policies. Same shape as "knot emits SQL,
your host opens connections."