# knot — 03: extend the spec, migrate the live DB

The team wants knot to cover more than movies: video games,
podcasts, TV, and the messy webscraped mentions feed. Each
new domain is a file in `media_spec/` — `games.py`,
`podcasts.py`, `tv.py`, `webscraped.py`. Activating them is
one import: `import media_spec.full`.

That import IS the migration. It mutates the same shared
`spec` object the v1 notebooks (`01_deploy`, `02_ingest`) ran
against, growing it from **4 classes / 3 sources / 9 bindings**
(v1, movies only) to **17 classes / 14 sources / 56 bindings**
(full CKG).

knot doesn't own the migration runtime — `Spec.ddl()` emits
the canonical target schema, and we hand it to
[Atlas](https://atlasgo.io/) to produce reconciling SQL
against the live DB.

```
spec change (Python)  →  Spec.ddl()  →  atlas diff/apply  →  live DB
```

Same posture as the rest of the library: knot emits, the host
composes with the tools it already trusts.

In [2]:
import subprocess
from pathlib import Path

import pandas as pd
from _demo import SCHEMA, connect, reset_atlas_dev

In [3]:
# The spec as it stood after 01_deploy: base entities only, one
# source, no embeddings.
from media_spec import spec

print("BEFORE — classes:", list(spec.classes))
print("BEFORE — sources:", list(spec.sources))
print("BEFORE — Movie slots:", [s.name for s in spec.classes["Movie"].slots])

BEFORE — classes: ['Person', 'Movie', 'MovieCredit', 'DirectedMovie']
BEFORE — sources: ['imdb', 'tmdb', 'rottentomatoes']
BEFORE — Movie slots: ['canonical_id', 'title', 'year', 'director', 'runtime_minutes', 'title_embedding']

## Compose in `media_spec.full`

This single line is the entire spec change. The module mutates
the shared `spec` object — adds the `title_embedding VECTOR(384)`
slot to `Movie`, adds the `tmdb` source plus its bindings. No
fork, no v1/v2 duplication; one spec that grew.

In [4]:
import media_spec.full  # noqa: F401  — imported for side effect

print("AFTER — classes:", list(spec.classes))
print("AFTER — sources:", list(spec.sources))
print("AFTER — Movie slots:", [s.name for s in spec.classes["Movie"].slots])

AFTER — classes: ['Person', 'Movie', 'MovieCredit', 'DirectedMovie', 'Studio', 'Platform', 'Game', 'Release', 'GameCredit', 'Podcast', 'PodcastEpisode', 'PodcastCredit', 'Show', 'Season', 'TVEpisode', 'TVCredit', 'Mention']
AFTER — sources: ['imdb', 'tmdb', 'rottentomatoes', 'igdb', 'giant_bomb', 'steam', 'apple_podcasts', 'spotify', 'listennotes', 'tvdb', 'blog_review_aggregator', 'fan_wiki', 'letterboxd_user_reviews', 'reddit_film_discussion']
AFTER — Movie slots: ['canonical_id', 'title', 'year', 'director', 'runtime_minutes', 'title_embedding']

In [5]:
# Live postgres + Atlas dev DB. Atlas needs a clean throwaway DB
# to render the desired schema into; reset it each run.
pg, engine = connect()
reset_atlas_dev()

## Emit the new target schema → file Atlas can read

`include_views=False` because Atlas community doesn't manage
views, and knot's `_resolved` / `_all_sources` views use
`FILTER (WHERE …)` aggregates that some schema-diff parsers
don't accept. We rebuild views in a separate step after Atlas
finishes (idempotent `CREATE OR REPLACE`).

In [6]:
target_sql = Path("/tmp/knot_target.sql")
target_sql.write_text(spec.ddl(include_views=False))
print(f"wrote {target_sql} ({target_sql.stat().st_size} bytes)")

wrote /tmp/knot_target.sql (21886 bytes)

## `atlas schema diff` — read the proposed migration

Atlas introspects the live DB (`--from`), loads the target SQL
into the dev DB to render the desired state (`--to` +
`--dev-url`), and prints the reconciling SQL. Nothing is
applied yet — review step.

In [7]:
diff = subprocess.run(
    [
        "atlas",
        "schema",
        "diff",
        "--from",
        "postgres://knot:knot@localhost:5433/knot?sslmode=disable",
        "--to",
        f"file://{target_sql}",
        "--dev-url",
        "postgres://knot:knot@localhost:5433/atlas_dev?sslmode=disable",
        "-s",
        SCHEMA,
    ],
    capture_output=True,
    text=True,
    check=True,
)
print(diff.stdout)

-- Create "release_bindings" table
CREATE TABLE "knot_demo"."release_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "game" text NULL, "platform" text NULL, "release_date" date NULL, "region" text NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "release_bindings_current_idx" to table: "release_bindings"
CREATE INDEX "release_bindings_current_idx" ON "knot_demo"."release_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "release_bindings_source_idx" to table: "release_bindings"
CREATE INDEX "release_bindings_source_idx" ON "knot_demo"."release_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "game_bindings" table
CREATE TABLE "knot_demo"."game_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "title" text NULL, "release_year" integer NULL, "studio" text NULL, "genre" text NULL, "platform_summary" text NULL, "title_embedding" public.vector(384) NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "game_bindings_current_idx" to table: "game_bindings"
CREATE INDEX "game_bindings_current_idx" ON "knot_demo"."game_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "game_bindings_source_idx" to table: "game_bindings"
CREATE INDEX "game_bindings_source_idx" ON "knot_demo"."game_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "game_bindings_title_embedding_hnsw_idx" to table: "game_bindings"
CREATE INDEX "game_bindings_title_embedding_hnsw_idx" ON "knot_demo"."game_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "show_bindings" table
CREATE TABLE "knot_demo"."show_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "title" text NULL, "start_year" integer NULL, "end_year" integer NULL, "network" text NULL, "status" text NULL, "title_embedding" public.vector(384) NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "show_bindings_current_idx" to table: "show_bindings"
CREATE INDEX "show_bindings_current_idx" ON "knot_demo"."show_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "show_bindings_source_idx" to table: "show_bindings"
CREATE INDEX "show_bindings_source_idx" ON "knot_demo"."show_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "show_bindings_title_embedding_hnsw_idx" to table: "show_bindings"
CREATE INDEX "show_bindings_title_embedding_hnsw_idx" ON "knot_demo"."show_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "gamecredit_bindings" table
CREATE TABLE "knot_demo"."gamecredit_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "role" text NULL, "game" text NULL, "person" text NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "gamecredit_bindings_current_idx" to table: "gamecredit_bindings"
CREATE INDEX "gamecredit_bindings_current_idx" ON "knot_demo"."gamecredit_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "gamecredit_bindings_source_idx" to table: "gamecredit_bindings"
CREATE INDEX "gamecredit_bindings_source_idx" ON "knot_demo"."gamecredit_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "studio_bindings" table
CREATE TABLE "knot_demo"."studio_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "name" text NULL, "country" text NULL, "founded_year" integer NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "studio_bindings_current_idx" to table: "studio_bindings"
CREATE INDEX "studio_bindings_current_idx" ON "knot_demo"."studio_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "studio_bindings_source_idx" to table: "studio_bindings"
CREATE INDEX "studio_bindings_source_idx" ON "knot_demo"."studio_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "mention_bindings" table
CREATE TABLE "knot_demo"."mention_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "subject_movie" text NULL, "subject_person" text NULL, "text_excerpt" text NULL, "sentiment" text NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "mention_bindings_current_idx" to table: "mention_bindings"
CREATE INDEX "mention_bindings_current_idx" ON "knot_demo"."mention_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "mention_bindings_source_idx" to table: "mention_bindings"
CREATE INDEX "mention_bindings_source_idx" ON "knot_demo"."mention_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "season_bindings" table
CREATE TABLE "knot_demo"."season_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "show" text NULL, "season_number" integer NULL, "episode_count" integer NULL, "year" integer NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "season_bindings_current_idx" to table: "season_bindings"
CREATE INDEX "season_bindings_current_idx" ON "knot_demo"."season_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "season_bindings_source_idx" to table: "season_bindings"
CREATE INDEX "season_bindings_source_idx" ON "knot_demo"."season_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "platform_bindings" table
CREATE TABLE "knot_demo"."platform_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "name" text NULL, "manufacturer" text NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "platform_bindings_current_idx" to table: "platform_bindings"
CREATE INDEX "platform_bindings_current_idx" ON "knot_demo"."platform_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "platform_bindings_source_idx" to table: "platform_bindings"
CREATE INDEX "platform_bindings_source_idx" ON "knot_demo"."platform_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "podcast_bindings" table
CREATE TABLE "knot_demo"."podcast_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "title" text NULL, "publisher" text NULL, "language" text NULL, "category" text NULL, "start_year" integer NULL, "title_embedding" public.vector(384) NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "podcast_bindings_current_idx" to table: "podcast_bindings"
CREATE INDEX "podcast_bindings_current_idx" ON "knot_demo"."podcast_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "podcast_bindings_source_idx" to table: "podcast_bindings"
CREATE INDEX "podcast_bindings_source_idx" ON "knot_demo"."podcast_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "podcast_bindings_title_embedding_hnsw_idx" to table: "podcast_bindings"
CREATE INDEX "podcast_bindings_title_embedding_hnsw_idx" ON "knot_demo"."podcast_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "tvcredit_bindings" table
CREATE TABLE "knot_demo"."tvcredit_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "role" text NULL, "show" text NULL, "episode" text NULL, "person" text NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "tvcredit_bindings_current_idx" to table: "tvcredit_bindings"
CREATE INDEX "tvcredit_bindings_current_idx" ON "knot_demo"."tvcredit_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "tvcredit_bindings_source_idx" to table: "tvcredit_bindings"
CREATE INDEX "tvcredit_bindings_source_idx" ON "knot_demo"."tvcredit_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "studio" table
CREATE TABLE "knot_demo"."studio" ("canonical_id" text NOT NULL, "name" text NOT NULL, "country" text NULL, "founded_year" integer NULL, PRIMARY KEY ("canonical_id"));
-- Create "podcastcredit_bindings" table
CREATE TABLE "knot_demo"."podcastcredit_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "role" text NULL, "podcast" text NULL, "episode" text NULL, "person" text NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "podcastcredit_bindings_current_idx" to table: "podcastcredit_bindings"
CREATE INDEX "podcastcredit_bindings_current_idx" ON "knot_demo"."podcastcredit_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "podcastcredit_bindings_source_idx" to table: "podcastcredit_bindings"
CREATE INDEX "podcastcredit_bindings_source_idx" ON "knot_demo"."podcastcredit_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "tvepisode_bindings" table
CREATE TABLE "knot_demo"."tvepisode_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "season" text NULL, "episode_number" integer NULL, "title" text NULL, "air_date" date NULL, "runtime_minutes" integer NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "tvepisode_bindings_current_idx" to table: "tvepisode_bindings"
CREATE INDEX "tvepisode_bindings_current_idx" ON "knot_demo"."tvepisode_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "tvepisode_bindings_source_idx" to table: "tvepisode_bindings"
CREATE INDEX "tvepisode_bindings_source_idx" ON "knot_demo"."tvepisode_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "podcastepisode_bindings" table
CREATE TABLE "knot_demo"."podcastepisode_bindings" ("source_name" text NOT NULL, "source_identifier" text NOT NULL, "canonical_id" text NULL, "podcast" text NULL, "episode_number" integer NULL, "title" text NULL, "air_date" date NULL, "duration_minutes" integer NULL, "raw_payload" jsonb NOT NULL DEFAULT '{}', "er_metadata" jsonb NOT NULL DEFAULT '{}', "valid_from" timestamptz NOT NULL DEFAULT now(), "valid_to" timestamptz NULL, PRIMARY KEY ("source_name", "source_identifier", "valid_from"));
-- Create index "podcastepisode_bindings_current_idx" to table: "podcastepisode_bindings"
CREATE INDEX "podcastepisode_bindings_current_idx" ON "knot_demo"."podcastepisode_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "podcastepisode_bindings_source_idx" to table: "podcastepisode_bindings"
CREATE INDEX "podcastepisode_bindings_source_idx" ON "knot_demo"."podcastepisode_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "game" table
CREATE TABLE "knot_demo"."game" ("canonical_id" text NOT NULL, "title" text NOT NULL, "release_year" integer NULL, "studio" text NULL, "genre" text NULL, "platform_summary" text NULL, "title_embedding" public.vector(384) NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_game_studio" FOREIGN KEY ("studio") REFERENCES "knot_demo"."studio" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "game_title_embedding_hnsw_idx" to table: "game"
CREATE INDEX "game_title_embedding_hnsw_idx" ON "knot_demo"."game" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "gamecredit" table
CREATE TABLE "knot_demo"."gamecredit" ("canonical_id" text NOT NULL, "role" text NOT NULL, "game" text NULL, "person" text NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_gamecredit_game" FOREIGN KEY ("game") REFERENCES "knot_demo"."game" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_gamecredit_person" FOREIGN KEY ("person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "mention" table
CREATE TABLE "knot_demo"."mention" ("canonical_id" text NOT NULL, "subject_movie" text NULL, "subject_person" text NULL, "text_excerpt" text NULL, "sentiment" text NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_mention_subject_movie" FOREIGN KEY ("subject_movie") REFERENCES "knot_demo"."movie" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_mention_subject_person" FOREIGN KEY ("subject_person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "podcast" table
CREATE TABLE "knot_demo"."podcast" ("canonical_id" text NOT NULL, "title" text NOT NULL, "publisher" text NULL, "language" text NULL, "category" text NULL, "start_year" integer NULL, "title_embedding" public.vector(384) NULL, PRIMARY KEY ("canonical_id"));
-- Create index "podcast_title_embedding_hnsw_idx" to table: "podcast"
CREATE INDEX "podcast_title_embedding_hnsw_idx" ON "knot_demo"."podcast" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "podcastepisode" table
CREATE TABLE "knot_demo"."podcastepisode" ("canonical_id" text NOT NULL, "podcast" text NULL, "episode_number" integer NULL, "title" text NULL, "air_date" date NULL, "duration_minutes" integer NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_podcastepisode_podcast" FOREIGN KEY ("podcast") REFERENCES "knot_demo"."podcast" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "podcastcredit" table
CREATE TABLE "knot_demo"."podcastcredit" ("canonical_id" text NOT NULL, "role" text NOT NULL, "podcast" text NULL, "episode" text NULL, "person" text NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_podcastcredit_episode" FOREIGN KEY ("episode") REFERENCES "knot_demo"."podcastepisode" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_podcastcredit_person" FOREIGN KEY ("person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_podcastcredit_podcast" FOREIGN KEY ("podcast") REFERENCES "knot_demo"."podcast" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "platform" table
CREATE TABLE "knot_demo"."platform" ("canonical_id" text NOT NULL, "name" text NOT NULL, "manufacturer" text NULL, PRIMARY KEY ("canonical_id"));
-- Create "release" table
CREATE TABLE "knot_demo"."release" ("canonical_id" text NOT NULL, "game" text NULL, "platform" text NULL, "release_date" date NULL, "region" text NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_release_game" FOREIGN KEY ("game") REFERENCES "knot_demo"."game" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_release_platform" FOREIGN KEY ("platform") REFERENCES "knot_demo"."platform" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "show" table
CREATE TABLE "knot_demo"."show" ("canonical_id" text NOT NULL, "title" text NOT NULL, "start_year" integer NULL, "end_year" integer NULL, "network" text NULL, "status" text NULL, "title_embedding" public.vector(384) NULL, PRIMARY KEY ("canonical_id"));
-- Create index "show_title_embedding_hnsw_idx" to table: "show"
CREATE INDEX "show_title_embedding_hnsw_idx" ON "knot_demo"."show" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "season" table
CREATE TABLE "knot_demo"."season" ("canonical_id" text NOT NULL, "show" text NULL, "season_number" integer NULL, "episode_count" integer NULL, "year" integer NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_season_show" FOREIGN KEY ("show") REFERENCES "knot_demo"."show" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "tvepisode" table
CREATE TABLE "knot_demo"."tvepisode" ("canonical_id" text NOT NULL, "season" text NULL, "episode_number" integer NULL, "title" text NULL, "air_date" date NULL, "runtime_minutes" integer NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_tvepisode_season" FOREIGN KEY ("season") REFERENCES "knot_demo"."season" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "tvcredit" table
CREATE TABLE "knot_demo"."tvcredit" ("canonical_id" text NOT NULL, "role" text NOT NULL, "show" text NULL, "episode" text NULL, "person" text NULL, PRIMARY KEY ("canonical_id"), CONSTRAINT "fk_tvcredit_episode" FOREIGN KEY ("episode") REFERENCES "knot_demo"."tvepisode" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_tvcredit_person" FOREIGN KEY ("person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_tvcredit_show" FOREIGN KEY ("show") REFERENCES "knot_demo"."show" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION);

## `atlas schema apply` — land the change

`--auto-approve` for the demo. In production you'd review the
diff interactively, or commit it to a versioned-migrations
directory and let CI apply on merge.

In [8]:
result = subprocess.run(
    [
        "atlas",
        "schema",
        "apply",
        "--url",
        "postgres://knot:knot@localhost:5433/knot?sslmode=disable",
        "--to",
        f"file://{target_sql}",
        "--dev-url",
        "postgres://knot:knot@localhost:5433/atlas_dev?sslmode=disable",
        "-s",
        SCHEMA,
        "--auto-approve",
    ],
    capture_output=True,
    text=True,
    check=True,
)
print(result.stdout)

-- Planned Changes:
-- Create "release_bindings" table
CREATE TABLE "knot_demo"."release_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "game" text NULL,
  "platform" text NULL,
  "release_date" date NULL,
  "region" text NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "release_bindings_current_idx" to table: "release_bindings"
CREATE INDEX "release_bindings_current_idx" ON "knot_demo"."release_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "release_bindings_source_idx" to table: "release_bindings"
CREATE INDEX "release_bindings_source_idx" ON "knot_demo"."release_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "game_bindings" table
CREATE TABLE "knot_demo"."game_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "title" text NULL,
  "release_year" integer NULL,
  "studio" text NULL,
  "genre" text NULL,
  "platform_summary" text NULL,
  "title_embedding" public.vector(384) NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "game_bindings_current_idx" to table: "game_bindings"
CREATE INDEX "game_bindings_current_idx" ON "knot_demo"."game_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "game_bindings_source_idx" to table: "game_bindings"
CREATE INDEX "game_bindings_source_idx" ON "knot_demo"."game_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "game_bindings_title_embedding_hnsw_idx" to table: "game_bindings"
CREATE INDEX "game_bindings_title_embedding_hnsw_idx" ON "knot_demo"."game_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "show_bindings" table
CREATE TABLE "knot_demo"."show_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "title" text NULL,
  "start_year" integer NULL,
  "end_year" integer NULL,
  "network" text NULL,
  "status" text NULL,
  "title_embedding" public.vector(384) NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "show_bindings_current_idx" to table: "show_bindings"
CREATE INDEX "show_bindings_current_idx" ON "knot_demo"."show_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "show_bindings_source_idx" to table: "show_bindings"
CREATE INDEX "show_bindings_source_idx" ON "knot_demo"."show_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "show_bindings_title_embedding_hnsw_idx" to table: "show_bindings"
CREATE INDEX "show_bindings_title_embedding_hnsw_idx" ON "knot_demo"."show_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "gamecredit_bindings" table
CREATE TABLE "knot_demo"."gamecredit_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "role" text NULL,
  "game" text NULL,
  "person" text NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "gamecredit_bindings_current_idx" to table: "gamecredit_bindings"
CREATE INDEX "gamecredit_bindings_current_idx" ON "knot_demo"."gamecredit_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "gamecredit_bindings_source_idx" to table: "gamecredit_bindings"
CREATE INDEX "gamecredit_bindings_source_idx" ON "knot_demo"."gamecredit_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "studio_bindings" table
CREATE TABLE "knot_demo"."studio_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "name" text NULL,
  "country" text NULL,
  "founded_year" integer NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "studio_bindings_current_idx" to table: "studio_bindings"
CREATE INDEX "studio_bindings_current_idx" ON "knot_demo"."studio_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "studio_bindings_source_idx" to table: "studio_bindings"
CREATE INDEX "studio_bindings_source_idx" ON "knot_demo"."studio_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "mention_bindings" table
CREATE TABLE "knot_demo"."mention_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "subject_movie" text NULL,
  "subject_person" text NULL,
  "text_excerpt" text NULL,
  "sentiment" text NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "mention_bindings_current_idx" to table: "mention_bindings"
CREATE INDEX "mention_bindings_current_idx" ON "knot_demo"."mention_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "mention_bindings_source_idx" to table: "mention_bindings"
CREATE INDEX "mention_bindings_source_idx" ON "knot_demo"."mention_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "season_bindings" table
CREATE TABLE "knot_demo"."season_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "show" text NULL,
  "season_number" integer NULL,
  "episode_count" integer NULL,
  "year" integer NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "season_bindings_current_idx" to table: "season_bindings"
CREATE INDEX "season_bindings_current_idx" ON "knot_demo"."season_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "season_bindings_source_idx" to table: "season_bindings"
CREATE INDEX "season_bindings_source_idx" ON "knot_demo"."season_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "platform_bindings" table
CREATE TABLE "knot_demo"."platform_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "name" text NULL,
  "manufacturer" text NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "platform_bindings_current_idx" to table: "platform_bindings"
CREATE INDEX "platform_bindings_current_idx" ON "knot_demo"."platform_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "platform_bindings_source_idx" to table: "platform_bindings"
CREATE INDEX "platform_bindings_source_idx" ON "knot_demo"."platform_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "podcast_bindings" table
CREATE TABLE "knot_demo"."podcast_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "title" text NULL,
  "publisher" text NULL,
  "language" text NULL,
  "category" text NULL,
  "start_year" integer NULL,
  "title_embedding" public.vector(384) NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "podcast_bindings_current_idx" to table: "podcast_bindings"
CREATE INDEX "podcast_bindings_current_idx" ON "knot_demo"."podcast_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "podcast_bindings_source_idx" to table: "podcast_bindings"
CREATE INDEX "podcast_bindings_source_idx" ON "knot_demo"."podcast_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create index "podcast_bindings_title_embedding_hnsw_idx" to table: "podcast_bindings"
CREATE INDEX "podcast_bindings_title_embedding_hnsw_idx" ON "knot_demo"."podcast_bindings" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "tvcredit_bindings" table
CREATE TABLE "knot_demo"."tvcredit_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "role" text NULL,
  "show" text NULL,
  "episode" text NULL,
  "person" text NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "tvcredit_bindings_current_idx" to table: "tvcredit_bindings"
CREATE INDEX "tvcredit_bindings_current_idx" ON "knot_demo"."tvcredit_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "tvcredit_bindings_source_idx" to table: "tvcredit_bindings"
CREATE INDEX "tvcredit_bindings_source_idx" ON "knot_demo"."tvcredit_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "studio" table
CREATE TABLE "knot_demo"."studio" (
  "canonical_id" text NOT NULL,
  "name" text NOT NULL,
  "country" text NULL,
  "founded_year" integer NULL,
  PRIMARY KEY ("canonical_id")
);
-- Create "podcastcredit_bindings" table
CREATE TABLE "knot_demo"."podcastcredit_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "role" text NULL,
  "podcast" text NULL,
  "episode" text NULL,
  "person" text NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "podcastcredit_bindings_current_idx" to table: "podcastcredit_bindings"
CREATE INDEX "podcastcredit_bindings_current_idx" ON "knot_demo"."podcastcredit_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "podcastcredit_bindings_source_idx" to table: "podcastcredit_bindings"
CREATE INDEX "podcastcredit_bindings_source_idx" ON "knot_demo"."podcastcredit_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "tvepisode_bindings" table
CREATE TABLE "knot_demo"."tvepisode_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "season" text NULL,
  "episode_number" integer NULL,
  "title" text NULL,
  "air_date" date NULL,
  "runtime_minutes" integer NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "tvepisode_bindings_current_idx" to table: "tvepisode_bindings"
CREATE INDEX "tvepisode_bindings_current_idx" ON "knot_demo"."tvepisode_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "tvepisode_bindings_source_idx" to table: "tvepisode_bindings"
CREATE INDEX "tvepisode_bindings_source_idx" ON "knot_demo"."tvepisode_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "podcastepisode_bindings" table
CREATE TABLE "knot_demo"."podcastepisode_bindings" (
  "source_name" text NOT NULL,
  "source_identifier" text NOT NULL,
  "canonical_id" text NULL,
  "podcast" text NULL,
  "episode_number" integer NULL,
  "title" text NULL,
  "air_date" date NULL,
  "duration_minutes" integer NULL,
  "raw_payload" jsonb NOT NULL DEFAULT '{}',
  "er_metadata" jsonb NOT NULL DEFAULT '{}',
  "valid_from" timestamptz NOT NULL DEFAULT now(),
  "valid_to" timestamptz NULL,
  PRIMARY KEY ("source_name", "source_identifier", "valid_from")
);
-- Create index "podcastepisode_bindings_current_idx" to table: "podcastepisode_bindings"
CREATE INDEX "podcastepisode_bindings_current_idx" ON "knot_demo"."podcastepisode_bindings" ("canonical_id") WHERE (valid_to IS NULL);
-- Create index "podcastepisode_bindings_source_idx" to table: "podcastepisode_bindings"
CREATE INDEX "podcastepisode_bindings_source_idx" ON "knot_demo"."podcastepisode_bindings" ("canonical_id", "source_name", "source_identifier") WHERE (valid_to IS NULL);
-- Create "game" table
CREATE TABLE "knot_demo"."game" (
  "canonical_id" text NOT NULL,
  "title" text NOT NULL,
  "release_year" integer NULL,
  "studio" text NULL,
  "genre" text NULL,
  "platform_summary" text NULL,
  "title_embedding" public.vector(384) NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_game_studio" FOREIGN KEY ("studio") REFERENCES "knot_demo"."studio" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "game_title_embedding_hnsw_idx" to table: "game"
CREATE INDEX "game_title_embedding_hnsw_idx" ON "knot_demo"."game" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "gamecredit" table
CREATE TABLE "knot_demo"."gamecredit" (
  "canonical_id" text NOT NULL,
  "role" text NOT NULL,
  "game" text NULL,
  "person" text NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_gamecredit_game" FOREIGN KEY ("game") REFERENCES "knot_demo"."game" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_gamecredit_person" FOREIGN KEY ("person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "mention" table
CREATE TABLE "knot_demo"."mention" (
  "canonical_id" text NOT NULL,
  "subject_movie" text NULL,
  "subject_person" text NULL,
  "text_excerpt" text NULL,
  "sentiment" text NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_mention_subject_movie" FOREIGN KEY ("subject_movie") REFERENCES "knot_demo"."movie" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_mention_subject_person" FOREIGN KEY ("subject_person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "podcast" table
CREATE TABLE "knot_demo"."podcast" (
  "canonical_id" text NOT NULL,
  "title" text NOT NULL,
  "publisher" text NULL,
  "language" text NULL,
  "category" text NULL,
  "start_year" integer NULL,
  "title_embedding" public.vector(384) NULL,
  PRIMARY KEY ("canonical_id")
);
-- Create index "podcast_title_embedding_hnsw_idx" to table: "podcast"
CREATE INDEX "podcast_title_embedding_hnsw_idx" ON "knot_demo"."podcast" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "podcastepisode" table
CREATE TABLE "knot_demo"."podcastepisode" (
  "canonical_id" text NOT NULL,
  "podcast" text NULL,
  "episode_number" integer NULL,
  "title" text NULL,
  "air_date" date NULL,
  "duration_minutes" integer NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_podcastepisode_podcast" FOREIGN KEY ("podcast") REFERENCES "knot_demo"."podcast" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "podcastcredit" table
CREATE TABLE "knot_demo"."podcastcredit" (
  "canonical_id" text NOT NULL,
  "role" text NOT NULL,
  "podcast" text NULL,
  "episode" text NULL,
  "person" text NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_podcastcredit_episode" FOREIGN KEY ("episode") REFERENCES "knot_demo"."podcastepisode" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_podcastcredit_person" FOREIGN KEY ("person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_podcastcredit_podcast" FOREIGN KEY ("podcast") REFERENCES "knot_demo"."podcast" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "platform" table
CREATE TABLE "knot_demo"."platform" (
  "canonical_id" text NOT NULL,
  "name" text NOT NULL,
  "manufacturer" text NULL,
  PRIMARY KEY ("canonical_id")
);
-- Create "release" table
CREATE TABLE "knot_demo"."release" (
  "canonical_id" text NOT NULL,
  "game" text NULL,
  "platform" text NULL,
  "release_date" date NULL,
  "region" text NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_release_game" FOREIGN KEY ("game") REFERENCES "knot_demo"."game" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_release_platform" FOREIGN KEY ("platform") REFERENCES "knot_demo"."platform" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "show" table
CREATE TABLE "knot_demo"."show" (
  "canonical_id" text NOT NULL,
  "title" text NOT NULL,
  "start_year" integer NULL,
  "end_year" integer NULL,
  "network" text NULL,
  "status" text NULL,
  "title_embedding" public.vector(384) NULL,
  PRIMARY KEY ("canonical_id")
);
-- Create index "show_title_embedding_hnsw_idx" to table: "show"
CREATE INDEX "show_title_embedding_hnsw_idx" ON "knot_demo"."show" USING hnsw ("title_embedding" vector_cosine_ops);
-- Create "season" table
CREATE TABLE "knot_demo"."season" (
  "canonical_id" text NOT NULL,
  "show" text NULL,
  "season_number" integer NULL,
  "episode_count" integer NULL,
  "year" integer NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_season_show" FOREIGN KEY ("show") REFERENCES "knot_demo"."show" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "tvepisode" table
CREATE TABLE "knot_demo"."tvepisode" (
  "canonical_id" text NOT NULL,
  "season" text NULL,
  "episode_number" integer NULL,
  "title" text NULL,
  "air_date" date NULL,
  "runtime_minutes" integer NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_tvepisode_season" FOREIGN KEY ("season") REFERENCES "knot_demo"."season" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "tvcredit" table
CREATE TABLE "knot_demo"."tvcredit" (
  "canonical_id" text NOT NULL,
  "role" text NOT NULL,
  "show" text NULL,
  "episode" text NULL,
  "person" text NULL,
  PRIMARY KEY ("canonical_id"),
  CONSTRAINT "fk_tvcredit_episode" FOREIGN KEY ("episode") REFERENCES "knot_demo"."tvepisode" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_tvcredit_person" FOREIGN KEY ("person") REFERENCES "knot_demo"."person" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "fk_tvcredit_show" FOREIGN KEY ("show") REFERENCES "knot_demo"."show" ("canonical_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

## Rebuild views via knot

Atlas community didn't touch views. `Spec.ddl()` is idempotent
throughout (`CREATE TABLE IF NOT EXISTS` / `CREATE OR REPLACE
VIEW`), so re-executing the full thing is safe — the table
statements are no-ops since Atlas brought them in line, and
the views get rebuilt against the new shape.

In [9]:
pg.execute(spec.ddl())

## Confirm — final shape

Tables (now including the new vector column on movie / movie_bindings),
indexes (including the HNSW index Atlas built), views regenerated.
Existing imdb data from 02_ingest is preserved through the migration.

In [10]:
pd.read_sql_query(
    """
    SELECT table_name AS name, table_type AS kind
    FROM information_schema.tables WHERE table_schema = %(schema)s
    UNION ALL
    SELECT viewname, 'VIEW' FROM pg_views WHERE schemaname = %(schema)s
    ORDER BY 2, 1
    """,
    engine,
    params={"schema": SCHEMA},
)

                     name        kind
0                    game  BASE TABLE
1           game_bindings  BASE TABLE
2              gamecredit  BASE TABLE
3     gamecredit_bindings  BASE TABLE
4                 mention  BASE TABLE
..                    ...         ...
94      tvcredit_resolved        VIEW
95  tvepisode_all_sources        VIEW
96  tvepisode_all_sources        VIEW
97     tvepisode_resolved        VIEW
98     tvepisode_resolved        VIEW

[99 rows x 2 columns]

In [11]:
pd.read_sql_query(
    """
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_schema = %(schema)s AND table_name = 'movie_bindings'
    ORDER BY ordinal_position
    """,
    engine,
    params={"schema": SCHEMA},
)

          column_name                 data_type
0         source_name                      text
1   source_identifier                      text
2        canonical_id                      text
3               title                      text
4                year                   integer
5            director                      text
6     runtime_minutes                   integer
7     title_embedding              USER-DEFINED
8         raw_payload                     jsonb
9         er_metadata                     jsonb
10         valid_from  timestamp with time zone
11           valid_to  timestamp with time zone

In [12]:
# HNSW index Atlas built from the spec's vector slot.
pd.read_sql_query(
    """
    SELECT indexname, indexdef
    FROM pg_indexes
    WHERE schemaname = %(schema)s AND tablename = 'movie_bindings'
    ORDER BY indexname
    """,
    engine,
    params={"schema": SCHEMA},
)

,indexname,indexdef
0,movie_bindings_current_idx,CREATE INDEX movie_bindings_current_idx ON kno...
1,movie_bindings_pkey,CREATE UNIQUE INDEX movie_bindings_pkey ON kno...
2,movie_bindings_source_idx,CREATE INDEX movie_bindings_source_idx ON knot...
3,movie_bindings_title_embedding_hnsw_idx,CREATE INDEX movie_bindings_title_embedding_hn...

In [13]:
# Imdb data survived the migration — `canonical_id` still NULL
# (ER hasn't run), `title_embedding` NULL (embedding worker
# hasn't run; both happen in 05_er).
pd.read_sql_query(
    f"""
    SELECT source_name,
           COUNT(*) AS rows,
           COUNT(title_embedding) AS embedded,
           COUNT(canonical_id) AS resolved
    FROM {SCHEMA}.movie_bindings
    GROUP BY source_name
    """,
    engine,
)

  source_name  rows  embedded  resolved
0        imdb    70         0         0

## What this didn't show (honest caveats)

- **Rename detection.** Atlas can't tell a rename from a
  drop-and-add. Use Atlas's `--declare-renames` HCL, or write
  a pre-migration script. Standard autogen blind spot.
- **Backfills.** Adding a `NOT NULL` column to a non-empty
  table needs an `UPDATE` first. Atlas surfaces the
  destructive op; the host owns the backfill.
- **Vector dim/metric changes.** `VECTOR(384) → VECTOR(768)`
  is a column-type change Atlas detects, but every existing
  embedding has to be recomputed by the embedding worker
  before the new column is meaningful.
- **Versioned migrations / down migrations / drift detection.**
  Atlas supports all of these via `atlas migrate` (versioned
  migration directory). This notebook uses `schema apply`
  for simplicity; production probably wants versioned.

The point isn't that this demo handles every case — it's
that the story is honest. knot emits the schema, Atlas
reconciles, the team owns the policies.