# knot — 03: extend the spec, migrate the live DB

The team wants to ship ER, which needs (a) a second source for
cross-source matching and (b) a vector column on `Movie` for
k-NN blocking. Both changes live in a new file —
`movies_spec/full.py` — that mutates the shared spec object
when imported. That file IS the migration: a Python module,
versioned alongside the rest of the codebase.

knot doesn't own the migration runtime — `Spec.ddl()` emits
the canonical target schema, and we hand it to
[Atlas](https://atlasgo.io/) to produce reconciling SQL
against the live DB.

```
spec change (Python)  →  Spec.ddl()  →  atlas diff/apply  →  live DB
```

Same posture as the rest of the library: knot emits, the host
composes with the tools it already trusts.

In [2]:
import subprocess
from pathlib import Path

import pandas as pd
import psycopg
from sqlalchemy import create_engine

In [3]:
# The spec as it stood after 01_deploy: base entities only, one
# source, no embeddings.
from movies_spec import spec

print("BEFORE — classes:", [c.name for c in spec.classes])
print("BEFORE — sources:", [s.name for s in spec.sources])
print("BEFORE — Movie slots:", [s.name for s in spec.classes[1].slots])

BEFORE — classes: ['Person', 'Movie']
BEFORE — sources: ['imdb']
BEFORE — Movie slots: ['canonical_id', 'title', 'year', 'director']

## Compose in `movies_spec.full`

This single line is the entire spec change. The module mutates
the shared `spec` object — adds the `title_embedding VECTOR(384)`
slot to `Movie`, adds the `tmdb` source plus its bindings. No
fork, no v1/v2 duplication; one spec that grew.

In [4]:
import movies_spec.full  # noqa: F401  — imported for side effect

print("AFTER — classes:", [c.name for c in spec.classes])
print("AFTER — sources:", [s.name for s in spec.sources])
print("AFTER — Movie slots:", [s.name for s in spec.classes[1].slots])

AFTER — classes: ['Person', 'Movie']
AFTER — sources: ['imdb', 'tmdb']
AFTER — Movie slots: ['canonical_id', 'title', 'year', 'director', 'title_embedding']

In [5]:
# Live postgres + atlas dev DB. Atlas needs a clean throwaway
# DB to render the desired schema into; we drop+recreate it each
# run so it starts empty.
pg = psycopg.connect(
    host="localhost",
    port=5433,
    user="knot",
    password="knot",
    dbname="knot",
    autocommit=True,
)
engine = create_engine("postgresql+psycopg://knot:knot@localhost:5433/knot")
with psycopg.connect(
    host="localhost",
    port=5433,
    user="knot",
    password="knot",
    dbname="postgres",
    autocommit=True,
) as admin:
    admin.execute("DROP DATABASE IF EXISTS atlas_dev")
    admin.execute("CREATE DATABASE atlas_dev")
SCHEMA = "knot_demo"
SCHEMA

'knot_demo'

## Emit the new target schema → file Atlas can read

`include_views=False` because Atlas community doesn't manage
views, and knot's `_resolved` / `_all_sources` views use
`FILTER (WHERE …)` aggregates that some schema-diff parsers
don't accept. We rebuild views in a separate step after Atlas
finishes (idempotent `CREATE OR REPLACE`).

In [6]:
target_sql = Path("/tmp/knot_target.sql")
target_sql.write_text(spec.ddl(schema=SCHEMA, include_views=False))
print(f"wrote {target_sql} ({target_sql.stat().st_size} bytes)")

wrote /tmp/knot_target.sql (2678 bytes)

## `atlas schema diff` — read the proposed migration

Atlas introspects the live DB (`--from`), loads the target SQL
into the dev DB to render the desired state (`--to` +
`--dev-url`), and prints the reconciling SQL. Nothing is
applied yet — review step.

In [7]:
diff = subprocess.run(
    [
        "atlas",
        "schema",
        "diff",
        "--from",
        "postgres://knot:knot@localhost:5433/knot?sslmode=disable",
        "--to",
        f"file://{target_sql}",
        "--dev-url",
        "postgres://knot:knot@localhost:5433/atlas_dev?sslmode=disable",
        "-s",
        SCHEMA,
    ],
    capture_output=True,
    text=True,
    check=True,
)
print(diff.stdout)

-- Modify "movie" table
ALTER TABLE "knot_demo"."movie" ADD COLUMN "title_embedding" public.vector(384) NULL;
-- Create index "movie_title_embedding_hnsw_idx" to table: "movie"
CREATE INDEX "movie_title_embedding_hnsw_idx" ON "knot_demo"."movie" USING hnsw ("title_embedding" vector_cosine_ops);
-- Modify "movie_bindings" table
ALTER TABLE "knot_demo"."movie_bindings" ADD COLUMN "title_embedding" public.vector(384) NULL;
-- Create index "movie_bindings_title_embedding_hnsw_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_title_embedding_hnsw_idx" ON "knot_demo"."movie_bindings" USING hnsw ("title_embedding" vector_cosine_ops);

## `atlas schema apply` — land the change

`--auto-approve` for the demo. In production you'd review the
diff interactively, or commit it to a versioned-migrations
directory and let CI apply on merge.

In [8]:
result = subprocess.run(
    [
        "atlas",
        "schema",
        "apply",
        "--url",
        "postgres://knot:knot@localhost:5433/knot?sslmode=disable",
        "--to",
        f"file://{target_sql}",
        "--dev-url",
        "postgres://knot:knot@localhost:5433/atlas_dev?sslmode=disable",
        "-s",
        SCHEMA,
        "--auto-approve",
    ],
    capture_output=True,
    text=True,
    check=True,
)
print(result.stdout)

-- Planned Changes:
-- Modify "movie" table
ALTER TABLE "knot_demo"."movie" ADD COLUMN "title_embedding" public.vector(384) NULL;
-- Create index "movie_title_embedding_hnsw_idx" to table: "movie"
CREATE INDEX "movie_title_embedding_hnsw_idx" ON "knot_demo"."movie" USING hnsw ("title_embedding" vector_cosine_ops);
-- Modify "movie_bindings" table
ALTER TABLE "knot_demo"."movie_bindings" ADD COLUMN "title_embedding" public.vector(384) NULL;
-- Create index "movie_bindings_title_embedding_hnsw_idx" to table: "movie_bindings"
CREATE INDEX "movie_bindings_title_embedding_hnsw_idx" ON "knot_demo"."movie_bindings" USING hnsw ("title_embedding" vector_cosine_ops);

## Rebuild views via knot

Atlas community didn't touch views. `Spec.ddl()` is idempotent
throughout (`CREATE TABLE IF NOT EXISTS` / `CREATE OR REPLACE
VIEW`), so re-executing the full thing is safe — the table
statements are no-ops since Atlas brought them in line, and
the views get rebuilt against the new shape.

In [9]:
pg.execute(spec.ddl(schema=SCHEMA))

## Confirm — final shape

Tables (now including the new vector column on movie / movie_bindings),
indexes (including the HNSW index Atlas built), views regenerated.
Existing imdb data from 02_ingest is preserved through the migration.

In [10]:
pd.read_sql_query(
    """
    SELECT table_name AS name, table_type AS kind
    FROM information_schema.tables WHERE table_schema = %(schema)s
    UNION ALL
    SELECT viewname, 'VIEW' FROM pg_views WHERE schemaname = %(schema)s
    ORDER BY 2, 1
    """,
    engine,
    params={"schema": SCHEMA},
)

                  name        kind
0                movie  BASE TABLE
1       movie_bindings  BASE TABLE
2               person  BASE TABLE
3      person_bindings  BASE TABLE
4        source_weight  BASE TABLE
5    movie_all_sources        VIEW
6    movie_all_sources        VIEW
7       movie_resolved        VIEW
8       movie_resolved        VIEW
9   person_all_sources        VIEW
10  person_all_sources        VIEW
11     person_resolved        VIEW
12     person_resolved        VIEW

In [11]:
pd.read_sql_query(
    """
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_schema = %(schema)s AND table_name = 'movie_bindings'
    ORDER BY ordinal_position
    """,
    engine,
    params={"schema": SCHEMA},
)

          column_name                 data_type
0         source_name                      text
1   source_identifier                      text
2        canonical_id                      text
3               title                      text
4                year                   integer
5            director                      text
6         raw_payload                     jsonb
7         er_metadata                     jsonb
8          valid_from  timestamp with time zone
9            valid_to  timestamp with time zone
10    title_embedding              USER-DEFINED

In [12]:
# HNSW index Atlas built from the spec's vector slot.
pd.read_sql_query(
    """
    SELECT indexname, indexdef
    FROM pg_indexes
    WHERE schemaname = %(schema)s AND tablename = 'movie_bindings'
    ORDER BY indexname
    """,
    engine,
    params={"schema": SCHEMA},
)

,indexname,indexdef
0,movie_bindings_current_idx,CREATE INDEX movie_bindings_current_idx ON kno...
1,movie_bindings_pkey,CREATE UNIQUE INDEX movie_bindings_pkey ON kno...
2,movie_bindings_source_idx,CREATE INDEX movie_bindings_source_idx ON knot...
3,movie_bindings_title_embedding_hnsw_idx,CREATE INDEX movie_bindings_title_embedding_hn...

In [13]:
# Imdb data survived the migration — `canonical_id` still NULL
# (ER hasn't run), `title_embedding` NULL (embedding worker
# hasn't run; both happen in 05_er).
pd.read_sql_query(
    f"""
    SELECT source_name,
           COUNT(*) AS rows,
           COUNT(title_embedding) AS embedded,
           COUNT(canonical_id) AS resolved
    FROM {SCHEMA}.movie_bindings
    GROUP BY source_name
    """,
    engine,
)

  source_name  rows  embedded  resolved
0        imdb    70         0         0

## What this didn't show (honest caveats)

- **Rename detection.** Atlas can't tell a rename from a
  drop-and-add. Use Atlas's `--declare-renames` HCL, or write
  a pre-migration script. Standard autogen blind spot.
- **Backfills.** Adding a `NOT NULL` column to a non-empty
  table needs an `UPDATE` first. Atlas surfaces the
  destructive op; the host owns the backfill.
- **Vector dim/metric changes.** `VECTOR(384) → VECTOR(768)`
  is a column-type change Atlas detects, but every existing
  embedding has to be recomputed by the embedding worker
  before the new column is meaningful.
- **Versioned migrations / down migrations / drift detection.**
  Atlas supports all of these via `atlas migrate` (versioned
  migration directory). This notebook uses `schema apply`
  for simplicity; production probably wants versioned.

The point isn't that this demo handles every case — it's
that the story is honest. knot emits the schema, Atlas
reconciles, the team owns the policies.